---
id: Service_Scribd
name: Service_Scribd
full: Scribd client library
description: Client libraries for the Scribd API.
list: dev
type: library
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: true
    role: lead
version:
  release: 1.0.0beta1
  api: 1.0.0
state:
  release: beta
  api: beta
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Http: ^2
      pear.horde.org/Horde_Translation: ^2.2
      pear.horde.org/Horde_Xml_Element: ^2
